In [ ]:
author = "Eetu Määttä"
studentNumber = "2420629"

In [2]:
import numpy as np
import numpy.linalg as la
import sympy as sp
import operator

x, y, z = sp.symbols('x, y, z')

In [61]:
#Functions
def matrix_solve(a,b):
    equations = []

    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            if isinstance(a[i,j], str):
                expr = sp.sympify(a[i, j])
                equations.append(sp.Eq(expr, b[i,j]))
        
    solution = sp.solve(equations, (x,y))
    if not solution:
        return 'Matrixes do not Equal, values cannot be assigned.'
    else:
        return solution

# Too lazy to rename the function, not about determinant anymore.
def determinant_matrix_solve(expression,i):
    A, B = sp.linear_eq_to_matrix(expression, i)
    C = sp.solve(expression,i)
    if not C:
        if not sp.linsolve((A,B),i):
            return "No solutions."
        else:
            sp.linsolve((A,B),i)
    else:
        return C
        
    
def create_square_nparray(arg, size):
    arr = []
    
    for i in range(size):
        arr_row = []
        for j in range(size):
            arr_row.append(arg(i,j))
        arr.append(arr_row)
        
    return np.array(arr)
        

In [17]:
#5.1.1 - 1

A = np.array([['x+y', 5],[-1, 'x-y']])
B = np.array([[3, 2],[-3, 1]])
C = np.array([[3, 5],[-1, 1]])

# (a
print(f'(A) A=B Values: ', matrix_solve(A,B))

# (b
print(f'(B) A=C Values: ', matrix_solve(A,C))

(A) A=B Values:  Matrixes do not Equal, values cannot be assigned.
(B) A=C Values:  {x: 2, y: 1}


In [5]:
#5.1.1 - 2

#Manually Written
A = np.array([[1-1, 1-2, 1-3],[2-1, 2-2, 2-3],[3-1, 3-2, 3-3]])
print('Hand Written:')
print(A)

#Func
print('Function Generated:')
print(create_square_nparray(operator.sub, 3))

Hand Written:
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]
Function Generated:
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]


In [6]:
#5.2.2 - 1

A = np.array([[-1, 2],[3, -5]], dtype=int)
B = np.array([[2, 0],[-1, 4]], dtype=int)

print(f'2A + 3B: \n{2*A + 3*B}')

print(f'A-B: \n{A - B}')

2A + 3B: 
[[4 4]
 [3 2]]
A-B: 
[[-3  2]
 [ 4 -9]]


In [7]:
#5.2.2 - 2

A = np.array([[-1, 1, -3],[-1, 5, 2],[-4, 2, 1]], dtype=int)
B = np.array([[-2, 2, -3],[-7, 4, 3],[4, 6, 1]], dtype=int)

print(f'A - B: \n{A - B}')
print(f'B - A: \n{B - A}')
print(f'2A + 5B: \n{2*A+5*B}')

A - B: 
[[ 1 -1  0]
 [ 6  1 -1]
 [-8 -4  0]]
B - A: 
[[-1  1  0]
 [-6 -1  1]
 [ 8  4  0]]
2A + 5B: 
[[-12  12 -21]
 [-37  30  19]
 [ 12  34   7]]


In [62]:
#8.1.1

print('8.1.1')
# (v
E = [2*x - 3*y - 5, 7*x + y - 3]
print('v:',sp.solve(E,[x, y]))

# (a
E = [2*x + 3*y - 11, 7*x - y - 4]
print('a:',sp.solve(E,[x,y]))

#8.1.2
print('8.1.2')
# (v1
E = [3*x - y + 5*z - 2, 7*x + 2*y + 3*z - 9, 4*x + y -7*z - 5]
print('v1:',sp.solve(E,[x, y, z]))

# (a
E = [2*x + y -3*z - 5, -3*x - y + 2*z - -7, 5*x + 2*y -4*z - 12]
print('a:',sp.solve(E,[x, y, z]))

#8.1.3
print('8.1.3')
# (v1
E = [x + y + z - 3, 2*x + y - z - 2, 4*x + 3*y + z - 5]
print('v1:',determinant_matrix_solve(E,[x, y, z]))

# (v2
E = [x + y + z - 3, 2*x + y - z - 2, 4*x + 3*y + z - 8]
print('v2:',determinant_matrix_solve(E,[x, y, z]))

# (a
E = [2*x + y -3*z - 5, -3*x - y + 2*z - -7, 5*x + 2*y -5*z - 12]
print('a:',determinant_matrix_solve(E,[x, y, z]))

# (b
E = [2*x + y -3*z - 5, -3*x - y + 2*z - -7, 5*x + 2*y -5*z - 11]
print('b:',determinant_matrix_solve(E,[x, y, z]))

8.1.1
v: {x: 14/23, y: -29/23}
a: {x: 1, y: 3}
8.1.2
v1: {x: 1, y: 1, z: 0}
a: {x: 2, y: 1, z: 0}
8.1.3
v1: No solutions.
v2: {x: 2*z - 1, y: 4 - 3*z}
a: {x: 2 - z, y: 5*z + 1}
b: No solutions.
